name: docker-build

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set IBCJuno chain name 🔧
        shell: bash
        run: echo "CHAIN_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')" >> $GITHUB_ENV

      - name: Set IBCJuno version 🔧
        shell: bash
        run: echo "GITHUB_VERSION=$(git describe --tags)" >> $GITHUB_ENV

      - name: Prepare tags 🏷️
        id: prep
        run: |
          DOCKER_IMAGE=${{ secrets.DOCKERHUB_IBCJUNO_REPO }}
          VERSION="${{env.GITHUB_VERSION}}"
          TAGS="${DOCKER_IMAGE}:ibcjuno-${VERSION}"
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Determine Dockerfile to use 🔍
        run: |
          export DOCKERFILE=Dockerfile.default
          echo "DOCKERFILE=${DOCKERFILE}" >> $GITHUB_ENV

      - name: Set up Docker Buildx 🧰
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub 👤
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push 📤
        uses: docker/build-push-action@v5
        with:
          context: .
          file: "./${{ env.DOCKERFILE }}"
          push: true
          tags: ${{ steps.prep.outputs.tags }}
